version: '3'

services:
  imandra-server:
    build: ./imandra-server
    ports:
      - "8080:8000"
      - "3000:3000"
    volumes:
      - ../tests/data:/tmp/data
      - ../verification:/opt/verification
      - ${HOME}/.imandra:/home/opam/.imandra
    working_dir: /opt/verification
    entrypoint:  ["imandra-http-server"]
    command: ["--skip-update"]
    # entrypoint: sleep infinity

  recon:
    build: ./recon
    environment:
      - "IMANDIRA_URL=http://imandra-server:3000"
      - "PARTICIPANT_NETWORK=docker_default"
    volumes:
      - ./recon:/opt/recon
      - ../tests/data:/tmp/data
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    working_dir: /opt/recon
    command: ./recon.py --data_dir /tmp/data --source "CN=a_1" --target "CN=b_1"
    # command: sleep infinity

  attacker:
    build: ./attacker
    environment:
      - "PARTICIPANT_NETWORK=docker_default"
    volumes:
      - ./attacker:/opt/attacker
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
    privileged: true
    working_dir: /opt/attacker
    command: ./capture.py /tmp 
    # command: sleep infinity


  simulator:
    build: ./simulator
    environment:
      - "ROS_SECURITY_ROOT_DIRECTORY=/tmp/credentials"
      - "ROS_SECURITY_ENABLE=true"
      - "ROS_SECURITY_STRATEGY=Enforce"
      - "PARTICIPANT_NETWORK=docker_default"
    volumes:
      - ./simulator:/opt/simulator
      - ../tests/credentials:/tmp/credentials
      - ../tests/data:/tmp/data
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
    privileged: true
    working_dir: /opt/simulator
    command: ./simulator.py --data_dir /tmp/data --ttl 3 --recon 10
    # command: sleep infinity
